name: Update GitHub Streak Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download streak image
        run: |
          curl -L "https://gitstreak.vercel.app/?user=bhavik-125&theme=midnight-purple&hide_border=false" --output streak.svg

      - name: Create assets directory
        run: mkdir -p assets

      - name: Move streak image
        run: mv streak.png assets/streak.png

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/streak.png
          git diff --cached --quiet || git commit -m "Update streak image"
          git push

